on:
  push:
    branches:
      - main
      - master
jobs:
  execute:
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    steps:
      - uses: MaximePremont/EpitechCriterionActions@master