name: Mirroring

on: [push, delete]

jobs:
  to_gitlab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:EpitechPromo2026/B-MUL-200-REN-2-1-myrpg-lucas.iglesia.git
          ssh_private_key:
            ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}
