name:
  "Repository state"
on : [push]
jobs:
  size:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
      - name: SIZE
        run: du -skh --exclude=".git"
  compilation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: make re > /dev/null && echo -e "\e[1m\e[32m\n► BUILD SUCCESS !\e[0m" || echo -e "\e[1m\e[31m\n► BUILD FAILED !\e[0m"